FormDemo/demoform/demoform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('news.urls'))
]

FormDemo/demoform/news/urls.py
from django.urls import path
from  .import views 
app_name = 'news'
urlpatterns = [
   
    path('',views.IndexClass.as_view(), name='index'),
    path('add/', views.PostClass.as_view(), name='add'), 
    path('save/', views.ClassSaveNew.as_view(), name='save'),
    path('email/', views.email_news, name='email'),
    path('process/',views.process, name='process'),
]

FormDemo/demoform/news/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255,blank=False,null=False)
    content = models.TextField(max_length=1000,blank=False,null=False)
    time_created = models.DateTimeField(default=timezone.datetime.now)
    
    def __str__(self):
        return self.title

FormDemo/demoform/news/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content',)
        widget ={
            'title': forms.TextField(attrs={'class': 'form-control'}),
            'content': forms.TextField(attrs={'class': 'form-content'}),
        }
        
class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'tieude'}))
    email= forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'phihoan', 'id' :'noidung'}))
    cc = forms.BooleanField(required=False)
    

FormDemo/demoform/news/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import PostForm, SendEmail
from django.views import View

# Create your views here.

class IndexClass(View):
    def get(self,request):
        
        ketqua = '12323'
        return HttpResponse(ketqua)


class ClassSaveNew(View):
    def get(self,request):
        a = PostForm()
        return render(request,'news/add_news.html',{ 'f':a })
    
    def post(self,request):
        g = PostForm(request.POST)
        if  g.is_valid():
            g.save()
            return HttpResponse("Success")
        else :
            return HttpResponse("Error")
    
    
def email_news(request):
    b = SendEmail()
    return render(request,'news/email.html',{ 'f':b})

def process(request): 
    if request.method == 'POST':
        m = SendEmail(request.POST)
        if m.is_valid():
            # tieude = m.cleaned_data["title"]
            # content = m.cleaned_data["content"]
            # cc = m.cleaned_data["cc"]
            # email = m.cleaned_data["email"]
            # context = { 'td':tieude, 'c':cc, 'b': content, 'd':email, }
            context2 = {'email_data': m}
            return render(request,'news/print_email.html', context2)
        
        else:
            return HttpResponse("form not validate")
    else:
        return HttpResponse("Error")        
            
        

FormDemo/demoform/news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        {% csrf_token %}
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>
        
        <input type="submit" value="add">
    </form>
</body>
</html>

FormDemo/demoform/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        .phihoan{ 
            padding: 20px;
        }
    </style>
    <form action="{% url 'news:process' %}" method="post">
        {{ f }}
    {% csrf_token %}
    <input type="submit" value="Send Email">
</form>

</body>
</html>

FormDemo/demoform/news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>

    <style>
        td{
            border: 1px solid black;
        }

    </style>
</head>
<body>
    <table>
        <tr>
            <td>Title</td>
            <td>Content</td>
            <td>Email</td>
            <td>CC</td>
        </tr>

        <tr>
            <td>{{ email_data.title }}</td>
            <td>{{ email_data.email }}</td>
            <td>{{ email_data.content }}</td>
            <td>{{ email_data.cc }}</td>
        </tr>
    </table>
</body>
</html>